/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * 					 edited by Johannes Müller, Dominik Berenspöhler
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * @details: Script for testing the functions of MPU6050.h and MPU6050.c
 * The angles relative to the horizontal axis (Z-axis of the sensor) are
 * displayed on the Piggybag's TFT display using the oscilloscope feature from
 * the BALO library. Additionally, the sensor-measured temperature in °C
 * is shown on the top line.
 *
 * Key features of the program:
 * - **MPU6050 Sensor**:
 *   - Measures angles (alpha and beta) relative to the horizontal plane.
 *   - Reads and provides temperature data in degrees Celsius.
 * - **TFT Display Integration**:
 *   - Visualizes angle data using the oscilloscope functionality of BALO.
 *   - Displays temperature readings in °C on the top of the screen.
 * - **Angle-Based LED Indicator**:
 *   - LED turns cyan when angles exceed ±10° from the zero position.
 *   - LED turns green for angles within ±10°.
 * - **Task Scheduling**:
 *   - Utilizes SysTick timers to manage periodic tasks for I2C communication,
 *     angle measurement, and temperature updates.
 *
 * NOTE: In BALO.h, '#define BALA2024' has been replaced with '#define PIGGYBAG'.
 * For information on the functions of the MPU6050 library, refer to the
 * corresponding documentation.
 ******************************************************************************
 */

// Include necessary header files
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stm32f4xx.h>
#include <mcalSysTick.h>
#include <mcalGPIO.h>
#include <mcalSPI.h>
#include <mcalI2C.h>
#include <RotaryPushButton.h>
#include <BALO.h>
#include <ST7735.h>
#include <MPU6050.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized. Initialize the FPU before using floating-point operations."
#endif

// Flags and timers for task scheduling
bool timerTrigger = false;
uint32_t Timer1 = 0UL;          // Main program timer
uint32_t ST7735_Timer = 0UL;    // TFT display-related timer
uint32_t I2C_Timer = 0UL;       // I2C communication timer

// Array for managing multiple timers
uint32_t *timerList[] = { &I2C_Timer, &ST7735_Timer };
size_t arraySize = sizeof(timerList) / sizeof(timerList[0]);

// Step task time in milliseconds
#define StepTaskTime 6

int main(void)
{
    // Task scheduling parameters
    uint32_t i2cTaskTime = 50UL; // I2C task period
    uint32_t temperatureRefresh = (i2cTaskTime * 0.2f);
    uint8_t i = 0;

    // Sensor data structure and other variables
    MPU6050_t MPU1;
    float anglefactor = 180 / _pi; // Conversion factor from radians to degrees
    float alphaBeta[2];            // Array to store angle data
    char output[10];               // Buffer for temperature output string
    int8_t ReturnVal=-1;
    // Initialize display and peripherals
    BALOsetup();
    LED_red_on;
    systickInit(SYSTICK_1MS);      // Initialize SysTick timer
    spiInit();                     // Initialize SPI
    tftInitR(INITR_REDTAB);        // Initialize TFT display

    // Set up display properties
    tftSetRotation(LANDSCAPE_FLIP);
    tftSetFont((uint8_t *)&SmallFont[0]);
    tftFillScreen(tft_BLACK);

    // Initialize rotary push button
    initRotaryPushButton();

    // Set timer interval
    systickSetMillis(&I2C_Timer, i2cTaskTime);

    // Initial display message

    tftPrintColor((char *)"MPU6050 Tmp.:", 0, 0, tft_MAGENTA);

    // Initialize MPU6050 sensor

#ifdef BALA2024
// MPU6050 I2C Bus
	#define 	MPUi2c		I2C2
#else
	#define 	MPUi2c 		I2C1
#endif
// this is the Init run
	do
	{
		if (timerTrigger == true)
	        {
	            systickUpdateTimerList((uint32_t *)timerList, arraySize);
	        }

	        // Check if I2C task is due
	        if (isSystickExpired(I2C_Timer))
	        {

	        	// Reset I2C timer
				systickSetTicktime(&I2C_Timer, i2cTaskTime);
				ReturnVal = mpuInit(&MPU1, MPUi2c, i2cAddr_MPU6050, 2, 3, MPU6050_LPBW_5, RESTART);
	        }
	} while (ReturnVal < 0);
	LED_red_off;
	// Reset I2C timer
	systickSetTicktime(&I2C_Timer, i2cTaskTime);
    while (1)
    {
        // Update timers if the trigger is set
        //TF if (timerTrigger && testVal >= 0)
    	if (timerTrigger == true)
        {
            systickUpdateTimerList((uint32_t *)timerList, arraySize);
        }

        // Check if I2C task is due
        if (isSystickExpired(I2C_Timer))
        {

        	// Reset I2C timer
            systickSetTicktime(&I2C_Timer, i2cTaskTime);


            // Read angles from MPU6050
            ReturnVal = mpuGetAngleFromAcceleration(&MPU1);
            alphaBeta[0] = MPU1.alpha_beta[0];
            alphaBeta[1] = MPU1.alpha_beta[1];

            // Update LED color based on angle thresholds
            if ((alphaBeta[0] * anglefactor < -10) || (alphaBeta[0] * anglefactor > 10) ||
                (alphaBeta[1] * anglefactor < -10) || (alphaBeta[1] * anglefactor > 10))
            {
                setRotaryColor(LED_CYAN); // Deviations greater than ±10° trigger cyan
            }
            else
            {
                setRotaryColor(LED_GREEN); // Otherwise, set green
            }

            // Display angle values on the oscilloscope
            AlBeOszi(alphaBeta);

            // Update temperature periodically
            i++;
            if (i % temperatureRefresh == 0)
            {
                mpuGetTemperature(&MPU1);
                sprintf(output, "%.1f C", MPU1.temperature_out);
                tftPrintColor((char *)output, (ST7735_TFTWIDTH - 20), 0, tft_MAGENTA);
                i = 0;
            }
        }
    }

    return 0; // Program end
}

