/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * 					 edited by Johannes Müller, Dominik Berenspöhler
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * @details: Script for testing the functions of MPU6050.h and MPU6050.c
 * The angles relative to the horizontal axis (Z-axis of the sensor) are
 * displayed on the Piggybag's TFT display using the oscilloscope feature from
 * the BALO library. Additionally, the sensor-measured temperature in °C
 * is shown on the top line.
 *
 * Key features of the program:
 * - **MPU6050 Sensor**:
 *   - Measures angles (alpha and beta) relative to the horizontal plane.
 *   - Reads and provides temperature data in degrees Celsius.
 * - **TFT Display Integration**:
 *   - Visualizes angle data using the oscilloscope functionality of BALO.
 *   - Displays temperature readings in °C on the top of the screen.
 * - **Angle-Based LED Indicator**:
 *   - LED turns cyan when angles exceed ±10° from the zero position.
 *   - LED turns green for angles within ±10°.
 * - **Task Scheduling**:
 *   - Utilizes SysTick timers to manage periodic tasks for I2C communication,
 *     angle measurement, and temperature updates.
 *
 * NOTE: In BALO.h, '#define BALA2024' has been replaced with '#define PIGGYBAG'.
 * For information on the functions of the MPU6050 library, refer to the
 * corresponding documentation.
 ******************************************************************************
 */

// Include necessary header files
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stm32f4xx.h>
#include <mcalSysTick.h>
#include <mcalGPIO.h>
#include <mcalSPI.h>
#include <mcalI2C.h>
#include <RotaryPushButton.h>
#include <BALO.h>
#include <ST7735.h>
#include <MPU6050.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized. Initialize the FPU before using floating-point operations."
#endif

#ifdef BALA2024
// MPU6050 I2C Bus
	#define 	MPUi2c		I2C2
#else
	#define 	MPUi2c 		I2C1
#endif
// this is the Init run





// Flags and timers for task scheduling
bool timerTrigger = false;

uint32_t Timer1 = 0UL;          // Main program timer
uint32_t ST7735_Timer = 0UL;    // TFT display-related timer
uint32_t I2C_Timer = 0UL;       // I2C communication timer



int main(void)
{
    // Task scheduling parameters
	uint32_t DispTaskTime = 70UL; // Display task period  statt:   uint32_t temperatureRefresh = (i2cTaskTime * 0.2f);
    uint32_t i2cTaskTime = 2UL; // I2C task period

    // Array for managing multiple timers
    uint32_t *timerList[] = {&Timer1, &I2C_Timer, &ST7735_Timer };
    size_t arraySize = sizeof(timerList) / sizeof(timerList[0]);

    // Sensor data structure and other variables
    MPU6050_t MPU1;
    float const _rad2deg = 180.0 / _pi; // Conversion factor from radians to degrees

    float AlphaBeta[2];            // Array to store angle data
    char outStr[32];               // Buffer for temperature output string
    int8_t ReturnVal=-1;			//  Return of Init mpu routine

    float temp;

    // Initialize display and peripherals
    BALOsetup();

    LED_red_on;						//start mpu init

    systickInit(SYSTICK_10MS);      // Initialize SysTick timer
    spiInit();                     // Initialize SPI
    tftInitR(INITR_REDTAB);        // Initialize TFT display

    // Set up display properties
    tftSetRotation(LANDSCAPE_FLIP);
    tftSetFont((uint8_t *)&SmallFont[0]);
    tftFillScreen(tft_BLACK);

    // Initialize rotary push button
    initRotaryPushButton();

    // Set timer interval
    systickSetMillis(&Timer1, DispTaskTime);
    systickSetMillis(&I2C_Timer, i2cTaskTime);

    // Initial display message

    tftPrintColor((char *)"MPU6050 Tmp.:", 0, 0, tft_GREEN);

    // Initialize MPU6050 sensor


	do
	{
		if (timerTrigger == true)
		{
			systickUpdateTimerList((uint32_t *)timerList, arraySize);
		}

		// Check if I2C task is due
		if (isSystickExpired(I2C_Timer))
		{

			// Reset I2C timer
			systickSetTicktime(&I2C_Timer, i2cTaskTime);
			ReturnVal = mpuInit(&MPU1, MPUi2c, i2cAddr_MPU6050, 3, 2, MPU6050_LPBW_94, RESTART);
		}
	} while (ReturnVal < 0);
	// Sensor Init finished


/*
 * Assemble Orientation of Sensor Modell Axis are Roll, Pitch,Yaw
 * Sensor Axis X = 1, Y =2, Z = 3 , negative Value are opposite Direction
 */
#ifdef BALA2024
	MPU1.RPY[0]= 2;				// MPU y Axis goes to the front
	MPU1.RPY[1]= 3;				// MPU z-Axis goes to the left side
	MPU1.RPY[2]= -1;			// MPU x-Axis goes down
#else
	// used default

#endif


#define Oszi
#ifdef Oszi
	MPU1.timebase = (float) i2cTaskTime* 10e-2;  // CycleTime for calc from Gyro to angle
#else
	MPU1.timebase = (float) DispTaskTime * 10e-2;  // CycleTime for calc from Gyro to angle
#endif



	LED_red_off;


	// Reset I2C timer
	systickSetTicktime(&I2C_Timer, i2cTaskTime);
    while (1)
    {
        // Update timers if the trigger is set
        //TF if (timerTrigger && testVal >= 0)
    	if (timerTrigger == true)
        {
            systickUpdateTimerList((uint32_t *)timerList, arraySize);
        }

        // Check if I2C task is due
        if (isSystickExpired(I2C_Timer))
        {

        	// Reset I2C timer
            systickSetTicktime(&I2C_Timer, i2cTaskTime);


            // Read angles from MPU6050
            //ReturnVal = mpuGetRPfromAccel(&MPU1);
            ReturnVal = mpuGetRPY(&MPU1);
            AlphaBeta[0] = MPU1.pitch;

            AlphaBeta[1] = MPU1.roll;


            // Update LED color based on angle thresholds
            if ((MPU1.pitch * _rad2deg < -10) || (MPU1.pitch * _rad2deg > 10) ||
                (MPU1.roll * _rad2deg < -10) || (MPU1.roll * _rad2deg > 10))
            {
                setRotaryColor(LED_CYAN); // Deviations greater than ±10° trigger cyan
            }
            else
            {
                setRotaryColor(LED_GREEN); // Otherwise, set green
            }

#ifdef Oszi
            // Display angle values on the oscilloscope
            AlBeOszi(AlphaBeta);
#endif
        }
        // Check if Timer1 task is due
        if (isSystickExpired(Timer1))
        {
        	// Reset Disp timer
        	systickSetTicktime(&Timer1, DispTaskTime);
        	temp = mpuTemp(&MPU1);
			sprintf(outStr, "%.1f C", temp);
			tftPrintColor((char *)outStr, (ST7735_TFTWIDTH - 20), 0, tft_GREEN);
#ifndef Oszi
			sprintf(outStr, "%3.2f %3.2f %3.2f", MPU1.accel[0], MPU1.accel[1],MPU1.accel[2]);
			tftPrintColor((char *)outStr, 0, 30, tft_YELLOW);
			sprintf(outStr, "%3.2f %3.2f %3.2f", MPU1.gyro[0], MPU1.gyro[1],MPU1.gyro[2]);
			tftPrintColor((char *)outStr, 0, 42, tft_RED);
			sprintf(outStr, "P: %3.2f R: %3.2f ", MPU1.pitch, MPU1.roll);
			tftPrintColor((char *)outStr, 0, 54, tft_GREEN);

#endif


        }
    }

    return 0; // Program end
}

